sudo: required
services:
  - docker

before_install:
  - docker build -t karthiksync/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true karthiksync/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react4"
  env: "DockerReact4-env"
  bucket_name: "elasticbeanstalk-us-east-1-437171724645"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "AKIAWLSLXEFSZTPIFI6M"
  secret_access_key: "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"